### ISSUE TITLE
RuntimeError: start() cannot be called before stop()

### ISSUE THREAD

**Issue by jameszw001** [nievesbrunet/video-stream-with-flask#1]
Nice work first of all. 

Here is what I am seeing when I refresh the page:
```

Error on request:
Traceback (most recent call last):
  File "/home/a/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/a/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/home/a/.local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/a/.local/lib/python2.7/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/a/Downloads/video-stream-with-flask/app.py", line 24, in gen
    profile = pipeline.start(config)
RuntimeError: start() cannot be called before stop()

```

**Comment by marianbrunet** [comment]
RuntimeError: start() cannot be called before stop(), means that the pipeline was already started, and was not stopped.

- Try killing the process and trying again.
```
ps -A | grep python
sudo kill my_process
```

- Make sure in the code there are a `pipeline start` and a `pipeline stop`.
